#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(
  cd "$(dirname "${BASH_SOURCE[0]}")/.." &&
  pwd
)"
cd "$ROOT_DIR"

source scripts/oauth-compose-context.sh
resolve_oauth_compose_context "$ROOT_DIR"

log() {
  printf '[oauth-reconcile] %s\n' "$*"
}

fail() {
  printf '[oauth-reconcile][FAIL] %s\n' "$*" >&2
  exit 1
}

log "Using Compose project: $OAUTH_COMPOSE_PROJECT"
log "Using the running stack's complete Compose topology."

for file in "${OAUTH_COMPOSE_FILES[@]}"; do
  log "Compose file: $file"
done

services="$("${OAUTH_COMPOSE[@]}" config --services)"

grep -Fxq 'apim-bootstrapper' <<<"$services" ||
  fail "apim-bootstrapper is absent from the resolved topology."

log "Effective bootstrapper volumes and environment:"

"${OAUTH_COMPOSE[@]}" config --format json |
  jq '{
    environment: .services["apim-bootstrapper"].environment,
    volumes: .services["apim-bootstrapper"].volumes
  }'

log "Rebuilding apim-bootstrapper with the current OAuth source."
"${OAUTH_COMPOSE[@]}" build apim-bootstrapper

log "Archiving OAuth state while preserving the managed API identity."

"${OAUTH_COMPOSE[@]}" run \
  --rm \
  --no-deps \
  -T \
  --entrypoint /bin/bash \
  apim-bootstrapper \
  -lc '
    set -Eeuo pipefail

    state_dir="/workspace/state"
    canonical_state="${state_dir}/oauth-business-controls.json"
    history_dir="${state_dir}/oauth-history"
    stamp="$(date +%Y%m%d-%H%M%S)"

    mkdir -p "${history_dir}"

    while IFS= read -r old_state; do
      [[ -n "${old_state}" ]] || continue

      backup_name="$(
        basename "${old_state}"
      ).${stamp}.json"

      cp "${old_state}" "${history_dir}/${backup_name}"

      echo \
        "[oauth-reconcile] Archived ${old_state} as " \
        "${history_dir}/${backup_name}"
    done < <(
      find "${state_dir}" \
        -maxdepth 3 \
        -type f \
        -name "oauth-business-controls.json" \
        2>/dev/null ||
        true
    )

    #
    # Never delete the only stored API UUID. When the canonical state is
    # absent, recover only the API identity from the newest history file.
    # OAuth applications, subscriptions and client credentials are then
    # regenerated by the normal setup module.
    #
    node src/seed-oauth-api-state.js

    [[ -s "${canonical_state}" ]] || {
      echo         "[oauth-reconcile][FAIL] API identity seed was not created."         >&2
      exit 1
    }

    node src/oauth-business-controls-setup.js

    generated_state="$(
      find "${state_dir}" \
        -maxdepth 3 \
        -type f \
        -name "oauth-business-controls.json" \
        2>/dev/null |
        head -n 1
    )"

    [[ -n "${generated_state}" && -s "${generated_state}" ]] || {
      echo \
        "[oauth-reconcile][FAIL] OAuth bootstrap did not generate state." \
        >&2
      exit 1
    }

    if [[ "${generated_state}" != "${canonical_state}" ]]; then
      cp "${generated_state}" "${canonical_state}"
    fi

    node - "${canonical_state}" <<"NODE"
const fs = require("fs");

const file = process.argv[2];
const state = JSON.parse(fs.readFileSync(file, "utf8"));
const serialized = JSON.stringify(state);

for (const expected of [
  "partner.alpha",
  "partner.beta",
  "telco.operations",
  "telco.product",
  "telco.admin"
]) {
  if (!serialized.includes(expected)) {
    console.error(
      `[oauth-reconcile][FAIL] Generated state lacks ${expected}`
    );
    process.exit(1);
  }
}

console.log(
  `[oauth-reconcile] Generated fresh OAuth state: ${file}`
);
NODE
  '

log "Ensuring SubscriberAuthorizationControlAPI has a fresh Gateway deployment."
bash scripts/ensure-oauth-api-deployment.sh

log "Reconciling API Product publication."

"${OAUTH_COMPOSE[@]}" run \
  --rm \
  --no-deps \
  -T \
  --entrypoint /bin/bash \
  apim-bootstrapper \
  -lc '
    set -Eeuo pipefail
    node src/developer-experience-setup.js
  '

mkdir -p .runtime

bash scripts/read-oauth-business-state.sh \
  > .runtime/oauth-business-controls.json

chmod 600 .runtime/oauth-business-controls.json

jq -e 'type == "object"' \
  .runtime/oauth-business-controls.json \
  >/dev/null ||
  fail "Exported OAuth state is not valid JSON."

if grep -q \
  'e58c71d1-e78b-4e3d-a31b-769dbfae8bd6' \
  .runtime/oauth-business-controls.json
then
  fail "Regenerated state still contains the deleted short-lived application ID."
fi

log "Fresh OAuth state exported to .runtime/oauth-business-controls.json"
log "OAuth applications, keys, subscriptions and Product were reconciled."
