[SERVICE]
    Flush        2
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /logs/telemetry/events.jsonl,/logs/telemetry/failed-billing.jsonl
    Tag               telco.structured
    Parser            json
    Read_from_Head    true
    Refresh_Interval  2

[INPUT]
    Name              tail
    Path              /logs/apim/*.log
    Tag               wso2.apim
    Read_from_Head    false
    Refresh_Interval  2
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Path              /logs/mi/*.log
    Tag               wso2.mi
    Read_from_Head    false
    Refresh_Interval  2
    Skip_Long_Lines   On

[OUTPUT]
    Name        loki
    Match       telco.structured
    Host        loki
    Port        3100
    Labels      job=telco.structured
    Line_Format json

[OUTPUT]
    Name        loki
    Match       wso2.apim
    Host        loki
    Port        3100
    Labels      job=wso2.apim
    Line_Format json

[OUTPUT]
    Name        loki
    Match       wso2.mi
    Host        loki
    Port        3100
    Labels      job=wso2.mi
    Line_Format json
