#!/usr/bin/env sh
set -eu
TARGET="${1:-/home/wso2carbon/wso2am-4.7.0/repository/conf/deployment.toml}"
TMP="${TARGET}.oauth-controls.tmp"
awk '
BEGIN { skip=0 }
/^\[apim\.jwt\]$/ { skip=1; next }
/^\[/ { if (skip) skip=0 }
!skip { print }
' "${TARGET}" > "${TMP}"
cat >> "${TMP}" <<'TOML'

# BEGIN TELCO OAUTH BUSINESS CONTROLS
# Backend JWT is generated by the authenticated APIM gateway. MI derives the
# authenticated subject from this gateway-issued context rather than trusting
# caller-supplied identity/persona headers.
[apim.jwt]
enable = true
encoding = "base64"
generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
claim_dialect = "http://wso2.org/claims"
convert_dialect = false
header = "X-JWT-Assertion"
signing_algorithm = "SHA256withRSA"
enable_user_claims = true
claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"
# END TELCO OAUTH BUSINESS CONTROLS
TOML
mv "${TMP}" "${TARGET}"
